version: "3.8"

services:
  database:
    image: mysql:latest
    volumes:
      - "mysql_data:/var/lib/mysql"
    container_name: note_hub_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: note_hub_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      
  # app:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   container_name: note_hub
  #   volumes:
  #     - .:/app

  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - database

volumes:
  mysql_data:
