const courses = [
    {
        regWorksheetId: 11773385,
        studentID: 24134,
        originalCalID: 72,
        courseID: 576,
        versionID: 1,
        credits: 1,
        formalCode: 'CSE 444-CSE(201)',
        courseTitle: 'Internet of Things Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773386,
        studentID: 24134,
        originalCalID: 72,
        courseID: 578,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 445-CSE(201)',
        courseTitle: 'Cloud Computing',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773387,
        studentID: 24134,
        originalCalID: 72,
        courseID: 579,
        versionID: 1,
        credits: 1,
        formalCode: 'CSE 446-CSE(201)',
        courseTitle: 'Cloud Computing Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773388,
        studentID: 24134,
        originalCalID: 72,
        courseID: 581,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 447-CSE(201)',
        courseTitle: 'Simulation and Modeling',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773389,
        studentID: 24134,
        originalCalID: 72,
        courseID: 582,
        versionID: 1,
        credits: 1,
        formalCode: 'CSE 448-CSE(201)',
        courseTitle: 'Simulation and Modeling Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773390,
        studentID: 24134,
        originalCalID: 72,
        courseID: 584,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 449-CSE(201)',
        courseTitle: 'Robotics',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773391,
        studentID: 24134,
        originalCalID: 72,
        courseID: 585,
        versionID: 1,
        credits: 1,
        formalCode: 'CSE 450-CSE(201)',
        courseTitle: 'Robotics Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773392,
        studentID: 24134,
        originalCalID: 72,
        courseID: 587,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 451-CSE(201)',
        courseTitle: 'Blockchain',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773393,
        studentID: 24134,
        originalCalID: 72,
        courseID: 588,
        versionID: 1,
        credits: 1,
        formalCode: 'CSE 452-CSE(201)',
        courseTitle: 'Blockchain Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773394,
        studentID: 24134,
        originalCalID: 72,
        courseID: 590,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 453-CSE(201)',
        courseTitle: 'Software Testing and Quality Assurance',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773395,
        studentID: 24134,
        originalCalID: 72,
        courseID: 591,
        versionID: 1,
        credits: 1,
        formalCode: 'CSE 454-CSE(201)',
        courseTitle: 'Software Testing and Quality Assurance Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773396,
        studentID: 24134,
        originalCalID: 72,
        courseID: 592,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 455-CSE(201)',
        courseTitle: 'Software Maintenance and Management',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773397,
        studentID: 24134,
        originalCalID: 72,
        courseID: 593,
        versionID: 1,
        credits: 1,
        formalCode: 'CSE 456-CSE(201)',
        courseTitle: 'Software Maintenance and Management Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773399,
        studentID: 24134,
        originalCalID: 72,
        courseID: 594,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 458',
        courseTitle: 'Industrial Training',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773285,
        studentID: 24134,
        originalCalID: 72,
        courseID: 630,
        versionID: 1,
        credits: 0,
        formalCode: 'EAP 009',
        courseTitle: 'English for Academic Purposes',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773329,
        studentID: 24134,
        originalCalID: 72,
        courseID: 1251,
        versionID: 1,
        credits: 3,
        formalCode: 'GED 303-CSE(181)',
        courseTitle: 'Sociology',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773367,
        studentID: 24134,
        originalCalID: 72,
        courseID: 1262,
        versionID: 1,
        credits: 3,
        formalCode: 'GED 403-CSE(201)',
        courseTitle: 'Business Communication',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773368,
        studentID: 24134,
        originalCalID: 72,
        courseID: 1265,
        versionID: 1,
        credits: 3,
        formalCode: 'GED 405-CSE(201)',
        courseTitle: 'Industrial and Operational Management',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773369,
        studentID: 24134,
        originalCalID: 72,
        courseID: 1268,
        versionID: 1,
        credits: 3,
        formalCode: 'GED 407-CSE(201)',
        courseTitle: 'Technology Entrepreneurship',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773364,
        studentID: 24134,
        originalCalID: 72,
        courseID: 1269,
        versionID: 1,
        credits: 2,
        formalCode: 'GED 409',
        courseTitle: 'Professional Ethics and Environmental Protection',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773365,
        studentID: 24134,
        originalCalID: 72,
        courseID: 1270,
        versionID: 1,
        credits: 2,
        formalCode: 'GED 411',
        courseTitle: 'Bangladesh Studies',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773400,
        studentID: 24134,
        originalCalID: 72,
        courseID: 2109,
        versionID: 1,
        credits: 0,
        formalCode: 'PSD-400',
        courseTitle: 'Professional Life Skills Development (PLSD)',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773318,
        studentID: 24134,
        originalCalID: 72,
        courseID: 454,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 303-CSE(181)',
        courseTitle: 'Microprocessors & Microcontrollers',
        acaCal_SectionID: 0,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: true,
        isCompleted: false
    },
    {
        regWorksheetId: 11773337,
        studentID: 24134,
        originalCalID: 72,
        courseID: 474,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 323',
        courseTitle: 'Computer and Cyber Security',
        acaCal_SectionID: 14357,
        sectionName: '221_D3',
        startHour1: '09',
        startMin1: '45',
        startAMPM1: 1,
        endHour1: '11',
        endMin1: '00',
        endAMPM1: 1,
        dayOne: 'Tue',
        dayOneId: 4,
        startHour2: '09',
        startMin2: '45',
        startAMPM2: 1,
        endHour2: '11',
        endMin2: '00',
        endAMPM2: 1,
        dayTwo: 'Thu',
        dayTwoId: 6,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773363,
        studentID: 24134,
        originalCalID: 72,
        courseID: 1259,
        versionID: 1,
        credits: 3,
        formalCode: 'GED 401-CSE(201)',
        courseTitle: 'Financial and Managerial Accounting',
        acaCal_SectionID: 14478,
        sectionName: '221_D13',
        startHour1: '02',
        startMin1: '00',
        startAMPM1: 2,
        endHour1: '03',
        endMin1: '15',
        endAMPM1: 2,
        dayOne: 'Tue',
        dayOneId: 4,
        startHour2: '02',
        startMin2: '00',
        startAMPM2: 2,
        endHour2: '03',
        endMin2: '15',
        endAMPM2: 2,
        dayTwo: 'Thu',
        dayTwoId: 6,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773327,
        studentID: 24134,
        originalCalID: 72,
        courseID: 463,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 312-CSE(181)',
        courseTitle: 'Computer Networking Lab',
        acaCal_SectionID: 14498,
        sectionName: '221_D20',
        startHour1: '11',
        startMin1: '00',
        startAMPM1: 1,
        endHour1: '01',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Tue',
        dayOneId: 4,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: 0,
        roomNo_1: 'J103-J103',
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773338,
        studentID: 24134,
        originalCalID: 72,
        courseID: 498,
        versionID: 1,
        credits: 3,
        formalCode: 'CSE 403-CSE(201)',
        courseTitle: 'Information System and Design',
        acaCal_SectionID: 14635,
        sectionName: '221_D2',
        startHour1: '12',
        startMin1: '15',
        startAMPM1: 2,
        endHour1: '01',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Wed',
        dayOneId: 5,
        startHour2: '12',
        startMin2: '15',
        startAMPM2: 2,
        endHour2: '01',
        endMin2: '30',
        endAMPM2: 2,
        dayTwo: 'Thu',
        dayTwoId: 6,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773333,
        studentID: 24134,
        originalCalID: 72,
        courseID: 476,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 324-CSE(201)',
        courseTitle: 'Integrated Design Project I',
        acaCal_SectionID: 14678,
        sectionName: '221_D9',
        startHour1: '08',
        startMin1: '30',
        startAMPM1: 1,
        endHour1: '11',
        endMin1: '00',
        endAMPM1: 1,
        dayOne: 'Wed',
        dayOneId: 5,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: 0,
        roomNo_1: 'L-106-L-106',
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    },
    {
        regWorksheetId: 11773319,
        studentID: 24134,
        originalCalID: 72,
        courseID: 455,
        versionID: 1,
        credits: 1,
        formalCode: 'CSE 304-CSE(181)',
        courseTitle: 'Microprocessors & Microcontrollers Lab',
        acaCal_SectionID: 14893,
        sectionName: '222_D4',
        startHour1: '11',
        startMin1: '00',
        startAMPM1: 1,
        endHour1: '12',
        endMin1: '40',
        endAMPM1: 2,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: 'K107-K107',
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false
    }
]

const section = [
    {
        acaCal_SectionID: 14075,
        sectionName: '223_D1',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '09',
        startMin1: '45',
        startAMPM1: 1,
        endHour1: '11',
        endMin1: '00',
        endAMPM1: 1,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '09',
        startMin2: '45',
        startAMPM2: 1,
        endHour2: '11',
        endMin2: '00',
        endAMPM2: 1,
        dayTwo: 'Tue',
        dayTwoId: 4,
        faculty_1: 'wahia.cse',
        faculty_2: 'wahia.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14076,
        sectionName: '223_D2',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '08',
        startMin1: '30',
        startAMPM1: 1,
        endHour1: '09',
        endMin1: '45',
        endAMPM1: 1,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '08',
        startMin2: '30',
        startAMPM2: 1,
        endHour2: '09',
        endMin2: '45',
        endAMPM2: 1,
        dayTwo: 'Tue',
        dayTwoId: 4,
        faculty_1: 'wahia.cse',
        faculty_2: 'wahia.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14289,
        sectionName: '223_D4',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '02',
        startMin1: '00',
        startAMPM1: 2,
        endHour1: '03',
        endMin1: '15',
        endAMPM1: 2,
        dayOne: 'Tue',
        dayOneId: 4,
        startHour2: '02',
        startMin2: '00',
        startAMPM2: 2,
        endHour2: '03',
        endMin2: '15',
        endAMPM2: 2,
        dayTwo: 'Thu',
        dayTwoId: 6,
        faculty_1: 'jui.cse',
        faculty_2: 'jui.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14738,
        sectionName: '223_D3',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '09',
        startMin1: '45',
        startAMPM1: 1,
        endHour1: '11',
        endMin1: '00',
        endAMPM1: 1,
        dayOne: 'Thu',
        dayOneId: 6,
        startHour2: '09',
        startMin2: '15',
        startAMPM2: 1,
        endHour2: '10',
        endMin2: '30',
        endAMPM2: 1,
        dayTwo: 'Fri',
        dayTwoId: 7,
        faculty_1: 'wahia.cse',
        faculty_2: 'wahia.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14883,
        sectionName: '222_D1',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '02',
        startMin1: '00',
        startAMPM1: 2,
        endHour1: '03',
        endMin1: '15',
        endAMPM1: 2,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '02',
        startMin2: '00',
        startAMPM2: 2,
        endHour2: '03',
        endMin2: '15',
        endAMPM2: 2,
        dayTwo: 'Wed',
        dayTwoId: 5,
        faculty_1: 'jarin.cse',
        faculty_2: 'jarin.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14884,
        sectionName: '222_D5',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '03',
        startMin1: '15',
        startAMPM1: 2,
        endHour1: '04',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '03',
        startMin2: '15',
        startAMPM2: 2,
        endHour2: '04',
        endMin2: '30',
        endAMPM2: 2,
        dayTwo: 'Tue',
        dayTwoId: 4,
        faculty_1: 'nazmus_shakib.cse',
        faculty_2: 'nazmus_shakib.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14885,
        sectionName: '222_D3',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '12',
        startMin1: '15',
        startAMPM1: 2,
        endHour1: '01',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Thu',
        dayOneId: 6,
        startHour2: '09',
        startMin2: '15',
        startAMPM2: 1,
        endHour2: '10',
        endMin2: '30',
        endAMPM2: 1,
        dayTwo: 'Fri',
        dayTwoId: 7,
        faculty_1: 'nazmus_shakib.cse',
        faculty_2: 'nazmus_shakib.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14886,
        sectionName: '222_D6',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '03',
        startMin1: '15',
        startAMPM1: 2,
        endHour1: '04',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '03',
        startMin2: '15',
        startAMPM2: 2,
        endHour2: '04',
        endMin2: '30',
        endAMPM2: 2,
        dayTwo: 'Wed',
        dayTwoId: 5,
        faculty_1: 'QUADER.CSE',
        faculty_2: 'QUADER.CSE',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14887,
        sectionName: '222_D4',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '08',
        startMin1: '30',
        startAMPM1: 1,
        endHour1: '09',
        endMin1: '45',
        endAMPM1: 1,
        dayOne: 'Wed',
        dayOneId: 5,
        startHour2: '08',
        startMin2: '30',
        startAMPM2: 1,
        endHour2: '09',
        endMin2: '45',
        endAMPM2: 1,
        dayTwo: 'Thu',
        dayTwoId: 6,
        faculty_1: 'QUADER.CSE',
        faculty_2: 'QUADER.CSE',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14888,
        sectionName: '222_D2',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '12',
        startMin1: '15',
        startAMPM1: 2,
        endHour1: '01',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Wed',
        dayOneId: 5,
        startHour2: '11',
        startMin2: '45',
        startAMPM2: 1,
        endHour2: '01',
        endMin2: '00',
        endAMPM2: 2,
        dayTwo: 'Fri',
        dayTwoId: 7,
        faculty_1: 'jui.cse',
        faculty_2: 'jui.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 31
    },
    {
        acaCal_SectionID: 14889,
        sectionName: '222_D10',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '08',
        startMin1: '30',
        startAMPM1: 1,
        endHour1: '09',
        endMin1: '45',
        endAMPM1: 1,
        dayOne: 'Thu',
        dayOneId: 6,
        startHour2: '08',
        startMin2: '00',
        startAMPM2: 1,
        endHour2: '09',
        endMin2: '15',
        endAMPM2: 1,
        dayTwo: 'Fri',
        dayTwoId: 7,
        faculty_1: 'sagufta.cse',
        faculty_2: 'sagufta.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 35
    },
    {
        acaCal_SectionID: 14890,
        sectionName: '222_D9',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '09',
        startMin1: '15',
        startAMPM1: 1,
        endHour1: '10',
        endMin1: '30',
        endAMPM1: 1,
        dayOne: 'Fri',
        dayOneId: 7,
        startHour2: '09',
        startMin2: '45',
        startAMPM2: 1,
        endHour2: '11',
        endMin2: '00',
        endAMPM2: 1,
        dayTwo: 'Sat',
        dayTwoId: 1,
        faculty_1: 'sagufta.cse',
        faculty_2: 'sagufta.cse',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 34
    },
    {
        acaCal_SectionID: 14891,
        sectionName: '222_D7',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '10',
        startMin1: '30',
        startAMPM1: 1,
        endHour1: '11',
        endMin1: '45',
        endAMPM1: 1,
        dayOne: 'Fri',
        dayOneId: 7,
        startHour2: '11',
        startMin2: '00',
        startAMPM2: 1,
        endHour2: '12',
        endMin2: '15',
        endAMPM2: 2,
        dayTwo: 'Sat',
        dayTwoId: 1,
        faculty_1: 'FATEMA_AKTER',
        faculty_2: 'FATEMA_AKTER',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 23
    },
    {
        acaCal_SectionID: 14892,
        sectionName: '222_D8',
        formalCode: 'CSE 303-CSE(181)',
        startHour1: '11',
        startMin1: '45',
        startAMPM1: 1,
        endHour1: '01',
        endMin1: '00',
        endAMPM1: 2,
        dayOne: 'Fri',
        dayOneId: 7,
        startHour2: '12',
        startMin2: '15',
        startAMPM2: 2,
        endHour2: '01',
        endMin2: '30',
        endAMPM2: 2,
        dayTwo: 'Sat',
        dayTwoId: 1,
        faculty_1: 'FATEMA_AKTER',
        faculty_2: 'FATEMA_AKTER',
        roomNo_1: null,
        roomNo_2: null,
        capacity: 35,
        occupied: 20
    }
]